### ISSUE TITLE
Support for VRFs

### ISSUE THREAD

**Issue by supertylerc** [checktheroads/hyperglass#15] opened 2019-08-22 23:39 UTC
Hi!  First, this is a beautiful and amazing project.  :)  Thank you for maintaining it!

The title says it all!  It would be nice if the supported commands could optionally support a VRF.  While this project certainly fits the needs of those who want to operate an "Internet LG" or an internal LG without VRFs, it does not work very well for networks that utilize VRFs.  I think it would be great if the possible commands could support a VRF on a per-device or per-"group" basis.

One could always setup a non-VRF BGP speaker (like a CE) VM with the other end being a VRF-aware BGP speaker (like a PE), but sometimes it's good to check a VRF from one VRF-aware point to another (e.g., PE to PE), especially when the VRF-aware speakers (e.g., PE routers) are already configured everywhere, but a CE-like device would need to be attached to every VRF-aware (PE) device for every VRF.

**Comment by checktheroads** [comment] 2019-08-23 01:03
Greetings! Thanks for the kind words. I recognize ya from twitter btw ;)

So - I intentionally made the commands user-overridable so that one could add the necessary modifiers (i.e. `show bgp ipv4 unicast vrf <vrf name>`). So you _can_ do it this way, however this is a per-NOS setting **currently**. Breaking this into a per-device option was requested a couple days ago in #13 and I have this on my list to implement as part of 1.0 which I am very close to being done with. Per my comment in #13, my plan is to move away from doing NOS-based commands, and do command "profiles" which can be set per-device. The defaults will probably be named after the NOS still (or similar), but one would be able to define any arbitrary name for a command profile and set it on the device config without breaking the Netmiko `type` argument.

Since your request came second I'm going to close this one out as a duplicate, you can keep an eye on #13 for any progress/notes, or feel free to join the [keybase team](https://keybase.io/team/hyperglass) I have going.

Thanks again!
-Matt

**Comment by checktheroads** [comment] 2019-08-23 01:04
Duplicate of #13

**Closed by checktheroads** 2019-08-23 01:04 UTC
Labels: enhancement
