### ISSUE TITLE
Filter on Location vs ASN

### ISSUE THREAD

**Issue by astlaurent** [checktheroads/hyperglass#30] opened 2020-04-08 19:54 UTC
Hi

Loving the project so far and i am trying to adapt this for a large data center deployment. by the very end of this we may have about 100 routers entered into the tool and they all will be under the same ASN. I would love it if there was a way to filter by location vs ASN on the looking glass page. This way we can tag all the routers as 1 location and have them grouped. For example pick DC-A from the list and it would show the 6 routers in DC-A, and so on.

Thank you

**Comment by checktheroads** [comment] 2020-04-08 20:14
Hi,

Are you using the 1.0 beta, or the “original” version (master branch)? I ask because in the 1.0 beta I’ve implemented a select component that supports searching, which might be “good enough” for your needs.

Thanks,
Matt

**Comment by astlaurent** [comment] 2020-04-08 20:28
good question. i just git cloned it per the instructions so i am sure i am using the master branch. I can switch over to the beta and check it out and see if it works out better the our purposes.

**Comment by checktheroads** [comment] 2020-04-08 20:32
Yeah, I would suggest using the beta. Docs are at [hyperglass.io](https://hyperglass.io). The main reason for the beta isn’t stability so much as me not having finished all the docs, or cleaned up some of the install process, etc. Let me know how it goes!

**Comment by checktheroads** [comment] 2020-04-08 20:37
Also, we’ve got a couple of chat options (Telegram, Gitter, Keybase) that various folks are using, should you want to join or need any help. Links should be on the v1 branch.

**Comment by astlaurent** [comment] 2020-04-09 00:39
i got v1.0 up and running and threw an ios xr router in it. I noticed when doing a bgp lookup it throws an error?

% Invalid input detected at '^' marker.

Log:
[DEBUG] 20200409 00:38:25 | hyperglass.execution.execute:216 | scrape_direct → Raw response for command "show bgp ipv4 unicast 69.7.0.0/20 | util egrep \\(BGP routing table entry|Path \\#|aggregated by|Origin |Community:|validity| from \\)":

                                                                                ^
% Invalid input detected at '^' marker.
[DEBUG] 20200409 00:38:25 | hyperglass.execution.execute:407 | response → Output for query: {"query_location": "sea_brdrrtr_01", "query_type": "bgp_route", "query_vrf": {"name": "default", "display_name": "Global", "info": {"bgp_aspath": {"enable": true, "file": null, "params": {"title": null}}, "bgp_community": {"enable": true, "file": null, "params": {"title": null}}, "bgp_route": {"enable": true, "file": null, "params": {"title": null}}, "ping": {"enable": true, "file": null, "params": {"title": null}}, "traceroute": {"enable": true, "file": null, "params": {"title": null}}}, "ipv4": {"source_address": "10.5.0.1", "access_list": [{"network": "10.0.0.0/8", "action": "deny", "ge": 8, "le": 32}, {"network": "192.168.0.0/16", "action": "deny", "ge": 16, "le": 32}, {"network": "172.16.0.0/12", "action": "deny", "ge": 12, "le": 32}, {"network": "0.0.0.0/0", "action": "permit", "ge": 8, "le": 24}], "force_cidr": true, "protocol": "ipv4_default", "version": 4}, "ipv6": {"source_address": "2600:2c05::1", "access_list": [{"network": "::/0", "action": "permit", "ge": 32, "le": 64}], "force_cidr": true, "protocol": "ipv6_default", "version": 6}}, "query_target": "69.7.0.0/20"}:
"\n

**Comment by checktheroads** [comment] 2020-04-11 16:16
Fixed the XR issue with commit `b1eac12`, @astlaurent confirmed via Gitter that the v1.0 select component is a good enough solution for the original issue topic, closing this out.

**Closed by checktheroads** 2020-04-11 16:16 UTC
Labels: enhancement

**Comment by astlaurent** [comment] 2020-04-15 03:29
FYI the new commit works perfect with xr. thanks!
